# Generated by Django 4.1.13 on 2024-08-26 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 13, 34, 43, 819874, tzinfo=datetime.timezone.utc)),
        ),
    ]
